In [1]:

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import csv
import os
from tqdm import tqdm
from seaborn import set_style

set_style("whitegrid")
#Import the csv file
dfhl=pd.read_csv('../data/dfhl.csv')
dfhl.time=pd.to_datetime(dfhl.time)
dfhl.open=dfhl.open.astype(float);dfhl.volume=dfhl.volume.astype(float);dfhl.MACD=dfhl.MACD.astype(float)
dfhl.MACD_Hist=dfhl.MACD_Hist.astype(float);dfhl.MACD_Signal=dfhl.MACD_Signal.astype(float)
dfhl

,time,open,volume,MACD,MACD_Hist,MACD_Signal,high,low
0,2023-05-31 15:59:00,418.105,5653492.0,-0.1139,-0.0884,-0.0254,418.105,417.76
1,2023-05-31 15:58:00,417.760,3337166.0,-0.1199,-0.1165,-0.0033,418.105,417.76
2,2023-05-31 15:57:00,417.795,2345699.0,-0.0906,-0.1164,0.0258,418.105,417.76
3,2023-05-31 15:56:00,417.885,1656396.0,-0.0556,-0.1105,0.0549,418.105,417.76
4,2023-05-31 15:55:00,417.970,2261461.0,-0.0192,-0.1018,0.0825,418.105,417.76
...,...,...,...,...,...,...,...,...
8965,2023-04-28 09:34:00,411.980,222984.0,0.1197,0.0466,0.0732,414.750,411.98
8966,2023-04-28 09:33:00,412.140,188445.0,0.1086,0.0471,0.0615,414.750,411.95
8967,2023-04-28 09:32:00,411.950,282485.0,0.0766,0.0269,0.0497,414.750,411.90
8968,2023-04-28 09:31:00,411.900,306992.0,0.0540,0.0109,0.0430,414.695,411.49
8969,2023-04-28 09:30:00,411.490,549418.0,0.0294,-0.0109,0.0403,414.695,411.49

In [84]:
#make two-hour window for 'open'
tdata=dfhl.copy()
open_price=[]
for t in range(120):
    column=[]
    for i in range(20):
        td = pd.Timedelta(i, "d")
        column.extend(tdata.loc[(tdata.time>=pd.Timestamp(2023,4,28)+td) &
                                                (tdata.time<pd.Timestamp(2023,4,28,15)+td)].open.shift(t).values[::-1][:-119])
    tdf=pd.DataFrame(columns=[f'open {t}'])
    tdf[f'open {t}']=column;open_price.append(tdf)
dfopen=pd.concat(open_price,axis=1)
dfopen

,open 0,open 1,open 2,open 3,open 4,open 5,open 6,open 7,open 8,open 9,...,open 110,open 111,open 112,open 113,open 114,open 115,open 116,open 117,open 118,open 119
0,411.490,411.900,411.950,412.140,411.980,412.010,412.250,412.190,412.190,412.220,...,413.7900,413.7750,413.7500,413.6200,413.7800,413.6800,413.6600,413.7100,413.6950,413.800
1,411.900,411.950,412.140,411.980,412.010,412.250,412.190,412.190,412.220,412.320,...,413.7750,413.7500,413.6200,413.7800,413.6800,413.6600,413.7100,413.6950,413.8000,413.745
2,411.950,412.140,411.980,412.010,412.250,412.190,412.190,412.220,412.320,412.310,...,413.7500,413.6200,413.7800,413.6800,413.6600,413.7100,413.6950,413.8000,413.7450,414.090
3,412.140,411.980,412.010,412.250,412.190,412.190,412.220,412.320,412.310,412.150,...,413.6200,413.7800,413.6800,413.6600,413.7100,413.6950,413.8000,413.7450,414.0900,414.260
4,411.980,412.010,412.250,412.190,412.190,412.220,412.320,412.310,412.150,412.040,...,413.7800,413.6800,413.6600,413.7100,413.6950,413.8000,413.7450,414.0900,414.2600,414.215
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2949,414.540,414.500,414.405,414.330,414.430,414.560,414.660,414.725,414.720,414.830,...,414.8800,414.9300,414.9500,415.0300,415.1299,415.0500,414.7400,414.7250,414.7172,414.790
2950,414.500,414.405,414.330,414.430,414.560,414.660,414.725,414.720,414.830,414.970,...,414.9300,414.9500,415.0300,415.1299,415.0500,414.7400,414.7250,414.7172,414.7900,414.760
2951,414.405,414.330,414.430,414.560,414.660,414.725,414.720,414.830,414.970,415.110,...,414.9500,415.0300,415.1299,415.0500,414.7400,414.7250,414.7172,414.7900,414.7600,414.700
2952,414.330,414.430,414.560,414.660,414.725,414.720,414.830,414.970,415.110,415.135,...,415.0300,415.1299,415.0500,414.7400,414.7250,414.7172,414.7900,414.7600,414.7000,414.690
2953,414.430,414.560,414.660,414.725,414.720,414.830,414.970,415.110,415.135,415.160,...,415.1299,415.0500,414.7400,414.7250,414.7172,414.7900,414.7600,414.7000,414.6900,414.620

In [85]:
#make two-hour window for 'volume'
volume=[]
for t in range(120):
    column=[]
    for i in range(20):
        td = pd.Timedelta(i, "d")
        column.extend(tdata.loc[(tdata.time>=pd.Timestamp(2023,4,28)+td) &
                                                (tdata.time<pd.Timestamp(2023,4,28,15)+td)].volume.shift(t).values[::-1][:-119])
    tdf=pd.DataFrame(columns=[f'volume {t}'])
    tdf[f'volume {t}']=column;volume.append(tdf)
dfvolume=pd.concat(volume,axis=1)
dfvolume

,volume 0,volume 1,volume 2,volume 3,volume 4,volume 5,volume 6,volume 7,volume 8,volume 9,...,volume 110,volume 111,volume 112,volume 113,volume 114,volume 115,volume 116,volume 117,volume 118,volume 119
0,549418.0,306992.0,282485.0,188445.0,222984.0,295634.0,136786.0,214095.0,198854.0,189935.0,...,147574.0,58785.0,111436.0,94438.0,127728.0,78350.0,71177.0,65881.0,109793.0,81471.0
1,306992.0,282485.0,188445.0,222984.0,295634.0,136786.0,214095.0,198854.0,189935.0,231573.0,...,58785.0,111436.0,94438.0,127728.0,78350.0,71177.0,65881.0,109793.0,81471.0,177864.0
2,282485.0,188445.0,222984.0,295634.0,136786.0,214095.0,198854.0,189935.0,231573.0,201470.0,...,111436.0,94438.0,127728.0,78350.0,71177.0,65881.0,109793.0,81471.0,177864.0,228794.0
3,188445.0,222984.0,295634.0,136786.0,214095.0,198854.0,189935.0,231573.0,201470.0,241958.0,...,94438.0,127728.0,78350.0,71177.0,65881.0,109793.0,81471.0,177864.0,228794.0,95477.0
4,222984.0,295634.0,136786.0,214095.0,198854.0,189935.0,231573.0,201470.0,241958.0,114675.0,...,127728.0,78350.0,71177.0,65881.0,109793.0,81471.0,177864.0,228794.0,95477.0,111226.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2949,131637.0,246621.0,244889.0,137200.0,274379.0,144541.0,232003.0,117732.0,182036.0,120638.0,...,114099.0,51282.0,154036.0,112021.0,109831.0,309713.0,130508.0,112161.0,104830.0,91524.0
2950,246621.0,244889.0,137200.0,274379.0,144541.0,232003.0,117732.0,182036.0,120638.0,428338.0,...,51282.0,154036.0,112021.0,109831.0,309713.0,130508.0,112161.0,104830.0,91524.0,118726.0
2951,244889.0,137200.0,274379.0,144541.0,232003.0,117732.0,182036.0,120638.0,428338.0,257366.0,...,154036.0,112021.0,109831.0,309713.0,130508.0,112161.0,104830.0,91524.0,118726.0,77265.0
2952,137200.0,274379.0,144541.0,232003.0,117732.0,182036.0,120638.0,428338.0,257366.0,280714.0,...,112021.0,109831.0,309713.0,130508.0,112161.0,104830.0,91524.0,118726.0,77265.0,83392.0
2953,274379.0,144541.0,232003.0,117732.0,182036.0,120638.0,428338.0,257366.0,280714.0,284921.0,...,109831.0,309713.0,130508.0,112161.0,104830.0,91524.0,118726.0,77265.0,83392.0,113844.0

In [86]:
#make two-hour window for 'MACD'
MACD=[]
for t in range(120):
    column=[]
    for i in range(20):
        td = pd.Timedelta(i, "d")
        column.extend(tdata.loc[(tdata.time>=pd.Timestamp(2023,4,28)+td) &
                                                (tdata.time<pd.Timestamp(2023,4,28,15)+td)].MACD.shift(t).values[::-1][:-119])
    tdf=pd.DataFrame(columns=[f'MACD {t}'])
    tdf[f'MACD {t}']=column;MACD.append(tdf)
dfMACD=pd.concat(MACD,axis=1)
dfMACD

,MACD 0,MACD 1,MACD 2,MACD 3,MACD 4,MACD 5,MACD 6,MACD 7,MACD 8,MACD 9,...,MACD 110,MACD 111,MACD 112,MACD 113,MACD 114,MACD 115,MACD 116,MACD 117,MACD 118,MACD 119
0,0.0294,0.0540,0.0766,0.1086,0.1197,0.1295,0.1547,0.1680,0.1765,0.1835,...,-0.0002,0.0177,0.0295,0.0281,0.0394,0.0398,0.0381,0.0403,0.0404,0.0484
1,0.0540,0.0766,0.1086,0.1197,0.1295,0.1547,0.1680,0.1765,0.1835,0.1949,...,0.0177,0.0295,0.0281,0.0394,0.0398,0.0381,0.0403,0.0404,0.0484,0.0497
2,0.0766,0.1086,0.1197,0.1295,0.1547,0.1680,0.1765,0.1835,0.1949,0.2008,...,0.0295,0.0281,0.0394,0.0398,0.0381,0.0403,0.0404,0.0484,0.0497,0.0777
3,0.1086,0.1197,0.1295,0.1547,0.1680,0.1765,0.1835,0.1949,0.2008,0.1904,...,0.0281,0.0394,0.0398,0.0381,0.0403,0.0404,0.0484,0.0497,0.0777,0.1123
4,0.1197,0.1295,0.1547,0.1680,0.1765,0.1835,0.1949,0.2008,0.1904,0.1712,...,0.0394,0.0398,0.0381,0.0403,0.0404,0.0484,0.0497,0.0777,0.1123,0.1345
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2949,0.3605,0.3619,0.3512,0.3329,0.3227,0.3214,0.3247,0.3288,0.3279,0.3322,...,-0.1098,-0.1079,-0.1037,-0.0928,-0.0752,-0.0670,-0.0845,-0.0985,-0.1089,-0.1100
2950,0.3619,0.3512,0.3329,0.3227,0.3214,0.3247,0.3288,0.3279,0.3322,0.3429,...,-0.1079,-0.1037,-0.0928,-0.0752,-0.0670,-0.0845,-0.0985,-0.1089,-0.1100,-0.1120
2951,0.3512,0.3329,0.3227,0.3214,0.3247,0.3288,0.3279,0.3322,0.3429,0.3586,...,-0.1037,-0.0928,-0.0752,-0.0670,-0.0845,-0.0985,-0.1089,-0.1100,-0.1120,-0.1171
2952,0.3329,0.3227,0.3214,0.3247,0.3288,0.3279,0.3322,0.3429,0.3586,0.3688,...,-0.0928,-0.0752,-0.0670,-0.0845,-0.0985,-0.1089,-0.1100,-0.1120,-0.1171,-0.1206
2953,0.3227,0.3214,0.3247,0.3288,0.3279,0.3322,0.3429,0.3586,0.3688,0.3745,...,-0.0752,-0.0670,-0.0845,-0.0985,-0.1089,-0.1100,-0.1120,-0.1171,-0.1206,-0.1275

In [87]:
#make two-hour window for 'Hist'
Hist=[]
for t in range(120):
    column=[]
    for i in range(20):
        td = pd.Timedelta(i, "d")
        column.extend(tdata.loc[(tdata.time>=pd.Timestamp(2023,4,28)+td) &
                                            (tdata.time<pd.Timestamp(2023,4,28,15)+td)].MACD_Hist.shift(t).values[::-1][:-119])
    tdf=pd.DataFrame(columns=[f'Hist {t}'])
    tdf[f'Hist {t}']=column;Hist.append(tdf)
dfHist=pd.concat(Hist,axis=1)
dfHist

,Hist 0,Hist 1,Hist 2,Hist 3,Hist 4,Hist 5,Hist 6,Hist 7,Hist 8,Hist 9,...,Hist 110,Hist 111,Hist 112,Hist 113,Hist 114,Hist 115,Hist 116,Hist 117,Hist 118,Hist 119
0,-0.0109,0.0109,0.0269,0.0471,0.0466,0.0450,0.0563,0.0556,0.0513,0.0466,...,0.0793,0.0777,0.0717,0.0562,0.0540,0.0435,0.0335,0.0286,0.0229,0.0247
1,0.0109,0.0269,0.0471,0.0466,0.0450,0.0563,0.0556,0.0513,0.0466,0.0464,...,0.0777,0.0717,0.0562,0.0540,0.0435,0.0335,0.0286,0.0229,0.0247,0.0208
2,0.0269,0.0471,0.0466,0.0450,0.0563,0.0556,0.0513,0.0466,0.0464,0.0419,...,0.0717,0.0562,0.0540,0.0435,0.0335,0.0286,0.0229,0.0247,0.0208,0.0390
3,0.0471,0.0466,0.0450,0.0563,0.0556,0.0513,0.0466,0.0464,0.0419,0.0251,...,0.0562,0.0540,0.0435,0.0335,0.0286,0.0229,0.0247,0.0208,0.0390,0.0589
4,0.0466,0.0450,0.0563,0.0556,0.0513,0.0466,0.0464,0.0419,0.0251,0.0048,...,0.0540,0.0435,0.0335,0.0286,0.0229,0.0247,0.0208,0.0390,0.0589,0.0649
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2949,0.0222,0.0188,0.0065,-0.0094,-0.0157,-0.0136,-0.0082,-0.0033,-0.0034,0.0007,...,-0.0162,-0.0115,-0.0058,0.0041,0.0173,0.0204,0.0023,-0.0093,-0.0158,-0.0135
2950,0.0188,0.0065,-0.0094,-0.0157,-0.0136,-0.0082,-0.0033,-0.0034,0.0007,0.0092,...,-0.0115,-0.0058,0.0041,0.0173,0.0204,0.0023,-0.0093,-0.0158,-0.0135,-0.0124
2951,0.0065,-0.0094,-0.0157,-0.0136,-0.0082,-0.0033,-0.0034,0.0007,0.0092,0.0199,...,-0.0058,0.0041,0.0173,0.0204,0.0023,-0.0093,-0.0158,-0.0135,-0.0124,-0.0140
2952,-0.0094,-0.0157,-0.0136,-0.0082,-0.0033,-0.0034,0.0007,0.0092,0.0199,0.0241,...,0.0041,0.0173,0.0204,0.0023,-0.0093,-0.0158,-0.0135,-0.0124,-0.0140,-0.0140
2953,-0.0157,-0.0136,-0.0082,-0.0033,-0.0034,0.0007,0.0092,0.0199,0.0241,0.0239,...,0.0173,0.0204,0.0023,-0.0093,-0.0158,-0.0135,-0.0124,-0.0140,-0.0140,-0.0167

In [88]:
#make two-hour window for 'Signal'
Signal=[]
for t in range(120):
    column=[]
    for i in range(20):
        td = pd.Timedelta(i, "d")
        column.extend(tdata.loc[(tdata.time>=pd.Timestamp(2023,4,28)+td) &
                                        (tdata.time<pd.Timestamp(2023,4,28,15)+td)].MACD_Signal.shift(t).values[::-1][:-119])
    tdf=pd.DataFrame(columns=[f'Signal {t}'])
    tdf[f'Signal {t}']=column;Signal.append(tdf)
dfSignal=pd.concat(Signal,axis=1)
dfSignal

,Signal 0,Signal 1,Signal 2,Signal 3,Signal 4,Signal 5,Signal 6,Signal 7,Signal 8,Signal 9,...,Signal 110,Signal 111,Signal 112,Signal 113,Signal 114,Signal 115,Signal 116,Signal 117,Signal 118,Signal 119
0,0.0403,0.0430,0.0497,0.0615,0.0732,0.0844,0.0985,0.1124,0.1252,0.1369,...,-0.0795,-0.0601,-0.0422,-0.0281,-0.0146,-0.0037,0.0046,0.0118,0.0175,0.0237
1,0.0430,0.0497,0.0615,0.0732,0.0844,0.0985,0.1124,0.1252,0.1369,0.1485,...,-0.0601,-0.0422,-0.0281,-0.0146,-0.0037,0.0046,0.0118,0.0175,0.0237,0.0289
2,0.0497,0.0615,0.0732,0.0844,0.0985,0.1124,0.1252,0.1369,0.1485,0.1589,...,-0.0422,-0.0281,-0.0146,-0.0037,0.0046,0.0118,0.0175,0.0237,0.0289,0.0386
3,0.0615,0.0732,0.0844,0.0985,0.1124,0.1252,0.1369,0.1485,0.1589,0.1652,...,-0.0281,-0.0146,-0.0037,0.0046,0.0118,0.0175,0.0237,0.0289,0.0386,0.0534
4,0.0732,0.0844,0.0985,0.1124,0.1252,0.1369,0.1485,0.1589,0.1652,0.1664,...,-0.0146,-0.0037,0.0046,0.0118,0.0175,0.0237,0.0289,0.0386,0.0534,0.0696
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2949,0.3383,0.3430,0.3447,0.3423,0.3384,0.3350,0.3330,0.3321,0.3313,0.3314,...,-0.0936,-0.0964,-0.0979,-0.0969,-0.0925,-0.0874,-0.0868,-0.0892,-0.0931,-0.0965
2950,0.3430,0.3447,0.3423,0.3384,0.3350,0.3330,0.3321,0.3313,0.3314,0.3337,...,-0.0964,-0.0979,-0.0969,-0.0925,-0.0874,-0.0868,-0.0892,-0.0931,-0.0965,-0.0996
2951,0.3447,0.3423,0.3384,0.3350,0.3330,0.3321,0.3313,0.3314,0.3337,0.3387,...,-0.0979,-0.0969,-0.0925,-0.0874,-0.0868,-0.0892,-0.0931,-0.0965,-0.0996,-0.1031
2952,0.3423,0.3384,0.3350,0.3330,0.3321,0.3313,0.3314,0.3337,0.3387,0.3447,...,-0.0969,-0.0925,-0.0874,-0.0868,-0.0892,-0.0931,-0.0965,-0.0996,-0.1031,-0.1066
2953,0.3384,0.3350,0.3330,0.3321,0.3313,0.3314,0.3337,0.3387,0.3447,0.3507,...,-0.0925,-0.0874,-0.0868,-0.0892,-0.0931,-0.0965,-0.0996,-0.1031,-0.1066,-0.1108

In [90]:
#X_train
df=pd.concat([dfopen,dfvolume,dfMACD,dfHist,dfSignal],axis=1)
df

In [101]:
#X_test
tdata=dfhl.copy()
open_price=[]
for t in range(120):
    column=[]
    column.extend(tdata.loc[(tdata.time>=pd.Timestamp(2023,5,18)) &
                                                (tdata.time<pd.Timestamp(2023,5,18,15))].open.shift(t).values[::-1][:-119])
    tdf=pd.DataFrame(columns=[f'open {t}'])
    tdf[f'open {t}']=column;open_price.append(tdf)
dfopen=pd.concat(open_price,axis=1)
volume=[]
for t in range(120):
    column=[]
    column.extend(tdata.loc[(tdata.time>=pd.Timestamp(2023,5,18)) &
                                                (tdata.time<pd.Timestamp(2023,5,18,15))].volume.shift(t).values[::-1][:-119])
    tdf=pd.DataFrame(columns=[f'volume {t}'])
    tdf[f'volume {t}']=column;volume.append(tdf)
dfvolume=pd.concat(volume,axis=1)
MACD=[]
for t in range(120):
    column=[]
    column.extend(tdata.loc[(tdata.time>=pd.Timestamp(2023,5,18)) &
                                                (tdata.time<pd.Timestamp(2023,5,18,15))].MACD.shift(t).values[::-1][:-119])
    tdf=pd.DataFrame(columns=[f'MACD {t}'])
    tdf[f'MACD {t}']=column;MACD.append(tdf)
dfMACD=pd.concat(MACD,axis=1)
Hist=[]
for t in range(120):
    column=[]
    column.extend(tdata.loc[(tdata.time>=pd.Timestamp(2023,5,18)) &
                                            (tdata.time<pd.Timestamp(2023,5,18,15))].MACD_Hist.shift(t).values[::-1][:-119])
    tdf=pd.DataFrame(columns=[f'Hist {t}'])
    tdf[f'Hist {t}']=column;Hist.append(tdf)
dfHist=pd.concat(Hist,axis=1)
Signal=[]
for t in range(120):
    column=[]
    column.extend(tdata.loc[(tdata.time>=pd.Timestamp(2023,5,18)) &
                                        (tdata.time<pd.Timestamp(2023,5,18,15))].MACD_Signal.shift(t).values[::-1][:-119])
    tdf=pd.DataFrame(columns=[f'Signal {t}'])
    tdf[f'Signal {t}']=column;Signal.append(tdf)
dfSignal=pd.concat(Signal,axis=1)
df=pd.concat([dfopen,dfvolume,dfMACD,dfHist,dfSignal],axis=1)
df

,open 0,open 1,open 2,open 3,open 4,open 5,open 6,open 7,open 8,open 9,...,Signal 110,Signal 111,Signal 112,Signal 113,Signal 114,Signal 115,Signal 116,Signal 117,Signal 118,Signal 119
0,414.9000,414.9250,414.8800,414.8150,414.900,414.875,414.780,414.950,414.995,415.255,...,0.1048,0.0926,0.0791,0.0608,0.0438,0.0288,0.0115,-0.0036,-0.0162,-0.0240
1,414.9250,414.8800,414.8150,414.9000,414.875,414.780,414.950,414.995,415.255,415.335,...,0.0926,0.0791,0.0608,0.0438,0.0288,0.0115,-0.0036,-0.0162,-0.0240,-0.0291
2,414.8800,414.8150,414.9000,414.8750,414.780,414.950,414.995,415.255,415.335,415.280,...,0.0791,0.0608,0.0438,0.0288,0.0115,-0.0036,-0.0162,-0.0240,-0.0291,-0.0348
3,414.8150,414.9000,414.8750,414.7800,414.950,414.995,415.255,415.335,415.280,415.440,...,0.0608,0.0438,0.0288,0.0115,-0.0036,-0.0162,-0.0240,-0.0291,-0.0348,-0.0386
4,414.9000,414.8750,414.7800,414.9500,414.995,415.255,415.335,415.280,415.440,415.295,...,0.0438,0.0288,0.0115,-0.0036,-0.0162,-0.0240,-0.0291,-0.0348,-0.0386,-0.0416
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,415.9200,416.0500,416.0922,416.0299,416.200,416.450,416.470,416.460,416.430,416.350,...,0.1663,0.1576,0.1525,0.1501,0.1499,0.1496,0.1497,0.1512,0.1515,0.1489
207,416.0500,416.0922,416.0299,416.2000,416.450,416.470,416.460,416.430,416.350,416.420,...,0.1576,0.1525,0.1501,0.1499,0.1496,0.1497,0.1512,0.1515,0.1489,0.1456
208,416.0922,416.0299,416.2000,416.4500,416.470,416.460,416.430,416.350,416.420,416.380,...,0.1525,0.1501,0.1499,0.1496,0.1497,0.1512,0.1515,0.1489,0.1456,0.1417
209,416.0299,416.2000,416.4500,416.4700,416.460,416.430,416.350,416.420,416.380,416.320,...,0.1501,0.1499,0.1496,0.1497,0.1512,0.1515,0.1489,0.1456,0.1417,0.1383
210,416.2000,416.4500,416.4700,416.4600,416.430,416.350,416.420,416.380,416.320,416.440,...,0.1499,0.1496,0.1497,0.1512,0.1515,0.1489,0.1456,0.1417,0.1383,0.1344

In [103]:
#Y_train
columnh=[];columnl=[]
for i in range(20):
    td = pd.Timedelta(i, "d")
    columnh.extend(tdata.loc[(tdata.time>=pd.Timestamp(2023,4,28,11,30)+td) &
                                        (tdata.time<=pd.Timestamp(2023,4,28,15)+td)].high.values[::-1])
    columnl.extend(tdata.loc[(tdata.time>=pd.Timestamp(2023,4,28,11,30)+td) &
                                        (tdata.time<=pd.Timestamp(2023,4,28,15)+td)].low.values[::-1])
    tdf=pd.DataFrame(columns=['High','Low'])
    tdf['High']=columnh;tdf['Low']=columnl
tdf

In [100]:
#Y_test
columnh=[];columnl=[]
columnh.extend(tdata.loc[(tdata.time>=pd.Timestamp(2023,5,18,11,30)) &
                                    (tdata.time<=pd.Timestamp(2023,5,18,15))].high.values[::-1])
columnl.extend(tdata.loc[(tdata.time>=pd.Timestamp(2023,5,18,11,30)) &
                                    (tdata.time<=pd.Timestamp(2023,5,18,15))].low.values[::-1])
tdf=pd.DataFrame(columns=['High','Low'])
tdf['High']=columnh;tdf['Low']=columnl
tdf

In [6]:
#New X_test for some other date
tdata=dfhl.copy()
open_price=[]
for t in range(120):
    column=[]
    column.extend(tdata.loc[(tdata.time>=pd.Timestamp(2023,5,19)) &
                                                (tdata.time<pd.Timestamp(2023,5,19,15))].open.shift(t).values[::-1][:-119])
    tdf=pd.DataFrame(columns=[f'open {t}'])
    tdf[f'open {t}']=column;open_price.append(tdf)
dfopen=pd.concat(open_price,axis=1)
volume=[]
for t in range(120):
    column=[]
    column.extend(tdata.loc[(tdata.time>=pd.Timestamp(2023,5,19)) &
                                                (tdata.time<pd.Timestamp(2023,5,19,15))].volume.shift(t).values[::-1][:-119])
    tdf=pd.DataFrame(columns=[f'volume {t}'])
    tdf[f'volume {t}']=column;volume.append(tdf)
dfvolume=pd.concat(volume,axis=1)
MACD=[]
for t in range(120):
    column=[]
    column.extend(tdata.loc[(tdata.time>=pd.Timestamp(2023,5,19)) &
                                                (tdata.time<pd.Timestamp(2023,5,19,15))].MACD.shift(t).values[::-1][:-119])
    tdf=pd.DataFrame(columns=[f'MACD {t}'])
    tdf[f'MACD {t}']=column;MACD.append(tdf)
dfMACD=pd.concat(MACD,axis=1)
Hist=[]
for t in range(120):
    column=[]
    column.extend(tdata.loc[(tdata.time>=pd.Timestamp(2023,5,19)) &
                                            (tdata.time<pd.Timestamp(2023,5,19,15))].MACD_Hist.shift(t).values[::-1][:-119])
    tdf=pd.DataFrame(columns=[f'Hist {t}'])
    tdf[f'Hist {t}']=column;Hist.append(tdf)
dfHist=pd.concat(Hist,axis=1)
Signal=[]
for t in range(120):
    column=[]
    column.extend(tdata.loc[(tdata.time>=pd.Timestamp(2023,5,19)) &
                                        (tdata.time<pd.Timestamp(2023,5,19,15))].MACD_Signal.shift(t).values[::-1][:-119])
    tdf=pd.DataFrame(columns=[f'Signal {t}'])
    tdf[f'Signal {t}']=column;Signal.append(tdf)
dfSignal=pd.concat(Signal,axis=1)
df=pd.concat([dfopen,dfvolume,dfMACD,dfHist,dfSignal],axis=1)
df.to_csv('X_final.csv',index=False)
df

,open 0,open 1,open 2,open 3,open 4,open 5,open 6,open 7,open 8,open 9,...,Signal 110,Signal 111,Signal 112,Signal 113,Signal 114,Signal 115,Signal 116,Signal 117,Signal 118,Signal 119
0,420.1700,420.0900,419.8200,420.0600,420.1201,420.250,420.210,420.260,420.350,420.515,...,-0.1977,-0.2046,-0.2039,-0.1991,-0.1936,-0.1916,-0.1873,-0.1855,-0.1929,-0.2066
1,420.0900,419.8200,420.0600,420.1201,420.2500,420.210,420.260,420.350,420.515,420.370,...,-0.2046,-0.2039,-0.1991,-0.1936,-0.1916,-0.1873,-0.1855,-0.1929,-0.2066,-0.2259
2,419.8200,420.0600,420.1201,420.2500,420.2100,420.260,420.350,420.515,420.370,420.390,...,-0.2039,-0.1991,-0.1936,-0.1916,-0.1873,-0.1855,-0.1929,-0.2066,-0.2259,-0.2487
3,420.0600,420.1201,420.2500,420.2100,420.2600,420.350,420.515,420.370,420.390,420.380,...,-0.1991,-0.1936,-0.1916,-0.1873,-0.1855,-0.1929,-0.2066,-0.2259,-0.2487,-0.2695
4,420.1201,420.2500,420.2100,420.2600,420.3500,420.515,420.370,420.390,420.380,420.680,...,-0.1936,-0.1916,-0.1873,-0.1855,-0.1929,-0.2066,-0.2259,-0.2487,-0.2695,-0.2959
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,418.8600,418.8050,418.8200,418.6600,418.6800,418.750,418.880,418.960,418.920,418.950,...,0.0013,0.0044,0.0032,0.0011,-0.0019,-0.0029,-0.0006,0.0064,0.0154,0.0267
207,418.8050,418.8200,418.6600,418.6800,418.7500,418.880,418.960,418.920,418.950,418.805,...,0.0044,0.0032,0.0011,-0.0019,-0.0029,-0.0006,0.0064,0.0154,0.0267,0.0412
208,418.8200,418.6600,418.6800,418.7500,418.8800,418.960,418.920,418.950,418.805,418.930,...,0.0032,0.0011,-0.0019,-0.0029,-0.0006,0.0064,0.0154,0.0267,0.0412,0.0556
209,418.6600,418.6800,418.7500,418.8800,418.9600,418.920,418.950,418.805,418.930,418.990,...,0.0011,-0.0019,-0.0029,-0.0006,0.0064,0.0154,0.0267,0.0412,0.0556,0.0699
210,418.6800,418.7500,418.8800,418.9600,418.9200,418.950,418.805,418.930,418.990,418.940,...,-0.0019,-0.0029,-0.0006,0.0064,0.0154,0.0267,0.0412,0.0556,0.0699,0.0845

In [7]:
#New Y_test for some other date
tdata=dfhl.copy()
columnh=[];columnl=[]
columnh.extend(tdata.loc[(tdata.time>=pd.Timestamp(2023,5,19,11,30)) &
                                    (tdata.time<=pd.Timestamp(2023,5,19,15))].high.values[::-1])
columnl.extend(tdata.loc[(tdata.time>=pd.Timestamp(2023,5,19,11,30)) &
                                    (tdata.time<=pd.Timestamp(2023,5,19,15))].low.values[::-1])
tdf=pd.DataFrame(columns=['High','Low'])
tdf['High']=columnh;tdf['Low']=columnl
tdf.to_csv('Y_final.csv',index=False)
tdf

       High     Low
0    418.93  417.38
1    418.93  417.38
2    418.93  417.38
3    418.93  417.38
4    418.93  417.38
..      ...     ...
206  418.89  418.04
207  418.91  418.04
208  418.91  418.04
209  418.95  418.04
210  418.96  418.04

[211 rows x 2 columns]